tplProjectName: mobilebuilder_tpl_7_9_0
↓Menu [mobile.components.UIDynamicMenu-1562069116561]: 🗏 mobileMenus/Menu.yaml
↓ChatBot [mobile.components.UISharedComponent-1562052281347]: 🗏 mobileSharedComponents/ChatBot.yaml
↓Page [mobile.components.PageComponent-1562069093658]: 🗏 mobilePages/Page.yaml